name: Wiki
description: Wiki Pengembangan Proyek BlankOn
avatar: ../favicon.ico
theme: jekyll-theme-architect
url: http://dev.blankon.id
baseurl: ""
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.rst
    - script/cibuild
