version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run:
          name: install gem
          command: 'bundle install'
      - run:
          name: build jekyll
          command: 'bundle exec jekyll build'
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master